<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>emu8086ln</AssemblyName>
    <RootNamespace>Emu8086.App</RootNamespace>
    <Product>emu8086ln</Product>
    <Version>1.2.0</Version>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Emu8086.Core\Emu8086.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\app.ico" />
    <Resource Include="Assets\logo.png" />
  </ItemGroup>

  <ItemGroup>
    <None Update="config\**\*" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Library\**\*" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Examples\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
