using System.Text;

namespace Emu8086.Core.Assembler;

/// <summary>Produces the classic assembler listing (.lst) and symbol table (.symbol) text files.</summary>
public static class ListingWriter
{
    private const int BytesPerRow = 6;

    /// <summary>
    /// Every source line with the address and bytes it produced. Lines generated by macros or
    /// includes are shown indented under the line that expanded them.
    /// </summary>
    public static string Listing(AssemblyResult result, string source, string fileName)
    {
        var lines = source.Replace("\r\n", "\n").Split('\n');
        var byLine = result.Listing.GroupBy(e => e.Line).ToDictionary(g => g.Key, g => g.ToList());
        var sb = new StringBuilder();
        sb.AppendLine($"; emu8086ln listing: {fileName}   format: {result.Format.ToString().ToUpperInvariant()}");
        sb.AppendLine("; line  segment:offset  bytes              source");
        sb.AppendLine();

        for (int i = 0; i < lines.Length; i++)
        {
            int number = i + 1;
            string text = lines[i].TrimEnd();
            if (!byLine.TryGetValue(number, out var entries))
            {
                sb.AppendLine($"{number,5}  {"",-14}  {"",-18} {text}");
                continue;
            }

            bool expanded = entries.Count > 1 || !Same(entries[0].Text, text);
            if (expanded) sb.AppendLine($"{number,5}  {"",-14}  {"",-18} {text}");
            foreach (var entry in entries)
            {
                var bytes = BytesOf(result, entry);
                string source1 = expanded ? "      " + entry.Text : text;
                for (int b = 0; b < bytes.Length; b += BytesPerRow)
                {
                    string hex = string.Join(" ", bytes.Skip(b).Take(BytesPerRow).Select(x => x.ToString("X2")));
                    string address = $"{SegmentName(result, entry.Segment)}:{entry.Offset + b:X4}";
                    string label = b == 0 ? source1 : "";
                    sb.AppendLine($"{(b == 0 && !expanded ? number.ToString() : ""),5}  {address,-14}  {hex,-18} {label}".TrimEnd());
                }
            }
        }

        sb.AppendLine();
        sb.Append(Symbols(result));
        return sb.ToString();
    }

    /// <summary>Symbol table: name, kind, address, size and element count.</summary>
    public static string Symbols(AssemblyResult result)
    {
        var sb = new StringBuilder();
        sb.AppendLine("; symbol table");
        sb.AppendLine($"; {"name",-24} {"kind",-10} {"address",-16} {"size",-6} length");
        foreach (var s in result.Symbols.Values.Where(s => !s.Name.StartsWith("??")).OrderBy(s => s.Segment).ThenBy(s => s.Value))
        {
            string address = s.Segment >= 0 ? $"{SegmentName(result, s.Segment)}:{s.Value:X4}" : $"{s.Value:X4}h ({s.Value})";
            string size = s.Kind == SymbolKind.Variable ? s.ElementSize.ToString() : s.Far ? "FAR" : s.Kind == SymbolKind.Constant ? "" : "NEAR";
            sb.AppendLine($"  {s.Name,-24} {s.Kind.ToString().ToUpperInvariant(),-10} {address,-16} {size,-6} {(s.Kind == SymbolKind.Variable ? s.Length : "")}");
        }
        return sb.ToString();
    }

    private static bool Same(string a, string b) =>
        string.Equals(Lexer.StripComment(a).Trim(), Lexer.StripComment(b).Trim(), StringComparison.OrdinalIgnoreCase);

    private static string SegmentName(AssemblyResult result, int index) =>
        index >= 0 && index < result.Segments.Count ? result.Segments[index].Name : "?";

    private static byte[] BytesOf(AssemblyResult result, ListingEntry entry)
    {
        var bytes = result.Segments[entry.Segment].Bytes;
        return Enumerable.Range(entry.Offset, entry.Length).Where(i => i < bytes.Count).Select(i => bytes[i]).ToArray();
    }
}
